const { ChatGoogleGenerativeAI } = require("@langchain/google-genai");
const { withGeminiRetry } = require("../../helpers/geminiRetry");
require("dotenv").config();

const gemini = new ChatGoogleGenerativeAI({
    model: "gemini-2.5-flash",
    apiKey: process.env.GOOGLE_API_KEY,
    temperature: 0.1 // Very low temp for strict verification
});

/**
 * Verifies the claims in the report against the evidence package.
 * Downgrades confidence or moves unsupported claims to open questions.
 * @param {object} report The synthesized report
 * @param {object} evidencePackage The evidence (timeline, raw claims, etc)
 * @returns {Promise<object>} The verified and potentially modified report
 */
async function verifyReport(report, evidencePackage) {
    if (!report || !report.claims || report.claims.length === 0) {
        return report;
    }

    const verifiedClaims = [];
    const openQuestions = [...(report.meta.openQuestions || [])];
    const conflicts = [];

    // Flatten evidence text for context
    const evidenceText = [
        ...(evidencePackage.timeline || []).map(e => `[Date: ${e.date}] ${e.description}`),
        ...(evidencePackage.claims || []).map(c => `[Source Claim] ${c.text}`)
    ].join('\n');

    // We verify each finding/claim from the synthesized report
    // Note: The synthesizer output mapped 'findings' to 'report.claims' or kept input claims.
    // In C-03 I mapped input claims to report.claims if available, OR used LLM findings.
    // If we used input claims (from summaries), they already have sourceIds.
    // If we used LLM findings, they have empty evidence.
    
    // Let's assume we need to verify the *findings* generated by the LLM (which might be hallucinations)
    // against the *ground truth* evidence (summaries/timeline).

    const claimsToVerify = report.claims || []; // These are the "findings"

    // Batch verification to save tokens/calls? Or one by one?
    // Batch is better for context.

    const claimsList = claimsToVerify.map((c, i) => `${i + 1}. ${c.text}`).join('\n');

    const prompt = `
    You are a strict legal verification engine.
    Your task is to verify the following CLAIMS against the provided EVIDENCE.

    EVIDENCE:
    ${evidenceText}

    CLAIMS TO VERIFY:
    ${claimsList}

    INSTRUCTIONS:
    For each claim:
    1. Determine if it is "supported" by the evidence, "contradicted" by the evidence, or "unsupported" (not mentioned).
    2. If supported, cite the specific evidence snippet.
    3. If contradicted, explain the conflict.

    OUTPUT FORMAT:
    Return strictly JSON array:
    [
        {
            "index": 1,
            "status": "supported|contradicted|unsupported",
            "reason": "explanation",
            "confidence": "high|medium|low"
        }
    ]
    `;

    try {
        const response = await withGeminiRetry(() => gemini.invoke(prompt));
        const cleanJson = response.content.replace(/```json\n?|```/g, "").trim();
        const verificationResults = JSON.parse(cleanJson);

        // Process results
        claimsToVerify.forEach((claim, index) => {
            const result = verificationResults.find(r => r.index === index + 1);
            
            if (!result) {
                // Default: keep as is if LLM missed it (rare)
                verifiedClaims.push(claim);
                return;
            }

            if (result.status === 'supported') {
                verifiedClaims.push({
                    ...claim,
                    confidence: result.confidence || 'high',
                    // We could add the reason as "evidence" text effectively
                    evidence: [{ sourceId: 'verification-pass', text: result.reason }]
                });
            } else if (result.status === 'contradicted') {
                // Move to conflicts or downgrade heavily
                conflicts.push({
                    claim: claim.text,
                    conflict: result.reason
                });
                // Also verify it but mark as low confidence? Or remove?
                // Let's keep it but mark low confidence and maybe flag it.
                verifiedClaims.push({
                    ...claim,
                    confidence: 'low',
                    evidence: [{ sourceId: 'verification-contradiction', text: result.reason }]
                });
            } else {
                // Unsupported
                // Move to open questions or keep with low confidence
                openQuestions.push(`Unverified claim: ${claim.text}`);
                // Do not include in verified findings? Or include with low confidence?
                // Spec says: "Unsupported claims downgraded or moved to openQuestions."
                // I'll move to openQuestions and NOT include in verified claims to keep report clean.
            }
        });

        return {
            ...report,
            claims: verifiedClaims,
            meta: {
                ...report.meta,
                openQuestions: openQuestions,
                conflicts: conflicts // Add this new field
            }
        };

    } catch (error) {
        console.error("Verification failed:", error);
        // Fallback: return original report
        return report;
    }
}

module.exports = { verifyReport };
